apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: slayer-servicemonitor
  namespace: monitoring
  labels:
    app: slayer-runner
    release: prometheus
spec:
  endpoints:
    - port: metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: slayer # target gitlab service